name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: Install Surge
        run: npm install -g surge
      - name: Cache RubyGems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-
      - name: Install Bundler
        run: |
          gem install bundler --no-document
          bundle config set deployment 'true';
          bundle config path vendor/bundle
          bundle install
      - name: Build Jekyll
        run: bundle exec jekyll build
      - name: Deploy
        run: surge ./_site ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
